package rewriter

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"
)

// JSCodeshiftResult captures the outcome of a jscodeshift transform run.
type JSCodeshiftResult struct {
	FilesModified    []string `json:"files_modified"`
	LinesRemoved     int      `json:"lines_removed"`
	RawOutput        string   `json:"raw_output"`
	TransformApplied bool     `json:"transform_applied"`
	Notes            string   `json:"notes"`
}

// transformScript returns a CommonJS jscodeshift transform as a plain string.
// It replaces:
//
//	if (flagClient.evaluate("FLAG_KEY", ctx)) { enabled } else { disabled }
//
// with either the enabled or disabled branch body depending on winningVariant.
func transformScript(flagKey, winningVariant string) string {
	useEnabled := strings.ToLower(winningVariant) == "true" ||
		strings.ToLower(winningVariant) == "on" ||
		strings.ToLower(winningVariant) == "enabled"

	branchIndex := "1" // default: use else branch (disabled)
	if useEnabled {
		branchIndex = "0" // use if/then branch (enabled)
	}

	return fmt.Sprintf(`/**
 * jscodeshift transform generated by Tombstone ast-rewriter.
 * Removes dead-code branches for flag: %s
 * Winning variant: %s
 */
module.exports = function(fileInfo, api) {
  var j = api.jscodeshift;
  var root = j(fileInfo.source);
  var flagKey = %q;
  var branchIndex = %s;

  root.find(j.IfStatement).forEach(function(path) {
    var test = path.node.test;

    // Match: flagClient.evaluate("FLAG_KEY", ...) at the top of the condition
    var isMatch = false;
    if (
      test.type === 'CallExpression' &&
      test.callee &&
      test.callee.type === 'MemberExpression' &&
      test.callee.property &&
      test.callee.property.name === 'evaluate' &&
      test.arguments &&
      test.arguments.length >= 1 &&
      test.arguments[0].type === 'StringLiteral' &&
      test.arguments[0].value === flagKey
    ) {
      isMatch = true;
    }

    // Also match: evaluate("FLAG_KEY", ...) called without an explicit client object
    if (!isMatch &&
      test.type === 'CallExpression' &&
      test.callee &&
      test.callee.type === 'Identifier' &&
      test.callee.name === 'evaluate' &&
      test.arguments &&
      test.arguments.length >= 1 &&
      test.arguments[0].type === 'StringLiteral' &&
      test.arguments[0].value === flagKey
    ) {
      isMatch = true;
    }

    if (!isMatch) { return; }

    var winningBody;
    if (branchIndex === 0) {
      // Use the consequent (if/then) branch
      winningBody = path.node.consequent;
    } else {
      // Use the alternate (else) branch, or an empty block when absent
      winningBody = path.node.alternate || j.blockStatement([]);
    }

    // Unwrap a block statement so we inline its statements directly
    if (winningBody.type === 'BlockStatement') {
      j(path).replaceWith(winningBody.body);
    } else {
      j(path).replaceWith([winningBody]);
    }
  });

  return root.toSource({ quote: 'single' });
};
`, flagKey, winningVariant, flagKey, branchIndex)
}

// RewriteWithJscodeshift runs jscodeshift over repoPath, applying a generated
// transform that removes dead-code branches for the given flagKey / winningVariant.
//
// If jscodeshift is not available on PATH the function returns a non-error result
// with TransformApplied=false and an install hint in Notes.
//
// When dryRun=true the --dry flag is forwarded to jscodeshift so no files are
// written on disk.
func RewriteWithJscodeshift(ctx context.Context, repoPath, flagKey, winningVariant string, dryRun bool) (*JSCodeshiftResult, error) {
	// 1. Check binary availability.
	jsBin, err := exec.LookPath("jscodeshift")
	if err != nil {
		return &JSCodeshiftResult{
			TransformApplied: false,
			Notes:            "jscodeshift not found on PATH - run: npm install -g jscodeshift",
		}, nil
	}

	// 2. Write the transform script to a temp file.
	tmpDir, err := os.MkdirTemp("", "tombstone-jscodeshift-*")
	if err != nil {
		return nil, fmt.Errorf("creating temp dir for transform: %w", err)
	}
	defer os.RemoveAll(tmpDir)

	transformPath := filepath.Join(tmpDir, "transform.cjs")
	script := transformScript(flagKey, winningVariant)
	if err := os.WriteFile(transformPath, []byte(script), 0o644); err != nil {
		return nil, fmt.Errorf("writing transform script: %w", err)
	}

	// 3. Build the jscodeshift command.
	args := []string{
		"--transform", transformPath,
		"--extensions", "ts,tsx,js,jsx",
		"--ignore-pattern", "node_modules",
		repoPath,
	}
	if dryRun {
		args = append([]string{"--dry"}, args...)
	}

	// 4. Execute with a 30-second timeout.
	runCtx, cancel := context.WithTimeout(ctx, 30*time.Second)
	defer cancel()

	cmd := exec.CommandContext(runCtx, jsBin, args...)
	out, runErr := cmd.CombinedOutput()
	rawOutput := string(out)

	// 5. Parse stdout/stderr for modified-file paths.
	// jscodeshift prints " MOD path/to/file" for every file it modifies.
	var modifiedFiles []string
	for _, line := range strings.Split(rawOutput, "\n") {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "MOD ") {
			filePath := strings.TrimSpace(strings.TrimPrefix(trimmed, "MOD "))
			if filePath != "" {
				modifiedFiles = append(modifiedFiles, filePath)
			}
		}
	}
	if modifiedFiles == nil {
		modifiedFiles = []string{}
	}

	// 6. Determine whether the transform actually applied.
	transformApplied := runErr == nil || len(modifiedFiles) > 0

	notes := "jscodeshift transform applied successfully"
	if runErr != nil {
		notes = fmt.Sprintf("jscodeshift exited with error: %v", runErr)
		transformApplied = false
	}
	if dryRun {
		notes += " (dry-run: no files written to disk)"
	}

	return &JSCodeshiftResult{
		FilesModified:    modifiedFiles,
		LinesRemoved:     len(modifiedFiles), // approximate: at least one hunk per modified file
		RawOutput:        rawOutput,
		TransformApplied: transformApplied,
		Notes:            notes,
	}, nil
}
