apiVersion: v1
kind: ConfigMap
metadata:
  name: tombstone-region-config
  labels:
    {{- include "tombstone.labels" . | nindent 4 }}
data:
  region: {{ .Values.global.region | default "us-east-1" | quote }}
  is-primary: {{ .Values.global.isPrimary | default true | quote }}
