apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - tombstone-operator/helmrepository.yaml
  - tombstone-operator/helmrelease.yaml
  - image-automation/policies.yaml
  - image-automation/update-automation.yaml
