apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../production/tombstone/namespace.yaml
  - ../production/tombstone/helmrelease.yaml
patchesStrategicMerge:
  - tombstone/helmrelease-patch.yaml
