// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: breakglass.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"
)

const consumeBreakGlassToken = `-- name: ConsumeBreakGlassToken :one
UPDATE break_glass_tokens
SET used = true, used_at = now(), used_by = $1
WHERE token_hash = $2
  AND used = false
  AND expires_at > now()
  AND ($3::text = '' OR project_id IS NULL OR project_id::text = $3::text)
RETURNING id, scope
`

type ConsumeBreakGlassTokenParams struct {
	UsedBy    sql.NullString
	TokenHash sql.NullString
	ProjectID string
}

type ConsumeBreakGlassTokenRow struct {
	ID    string
	Scope string
}

// $3 is always a plain string, "" meaning "no project scope requested" — a
// single static query using an empty-string sentinel, not "$3=”" alongside
// a same-parameter ::uuid cast in another branch: AUD-1 found that mixing
// two type contexts for one parameter within one statement is exactly what
// confuses lib/pq's extended-protocol type inference. Casting the COLUMN to
// text (not the parameter to uuid) keeps $3 in a single, consistent type
// context throughout.
func (q *Queries) ConsumeBreakGlassToken(ctx context.Context, arg ConsumeBreakGlassTokenParams) (ConsumeBreakGlassTokenRow, error) {
	row := q.db.QueryRowContext(ctx, consumeBreakGlassToken, arg.UsedBy, arg.TokenHash, arg.ProjectID)
	var i ConsumeBreakGlassTokenRow
	err := row.Scan(&i.ID, &i.Scope)
	return i, err
}

const createBreakGlassToken = `-- name: CreateBreakGlassToken :exec
INSERT INTO break_glass_tokens (token_hash, scope, created_by, expires_at, incident_ref, project_id)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateBreakGlassTokenParams struct {
	TokenHash   sql.NullString
	Scope       string
	CreatedBy   string
	ExpiresAt   time.Time
	IncidentRef sql.NullString
	ProjectID   sql.NullString
}

func (q *Queries) CreateBreakGlassToken(ctx context.Context, arg CreateBreakGlassTokenParams) error {
	_, err := q.db.ExecContext(ctx, createBreakGlassToken,
		arg.TokenHash,
		arg.Scope,
		arg.CreatedBy,
		arg.ExpiresAt,
		arg.IncidentRef,
		arg.ProjectID,
	)
	return err
}

const getBreakGlassTokenDiagnostics = `-- name: GetBreakGlassTokenDiagnostics :one
SELECT used, expires_at, project_id FROM break_glass_tokens WHERE token_hash = $1
`

type GetBreakGlassTokenDiagnosticsRow struct {
	Used      bool
	ExpiresAt time.Time
	ProjectID sql.NullString
}

func (q *Queries) GetBreakGlassTokenDiagnostics(ctx context.Context, tokenHash sql.NullString) (GetBreakGlassTokenDiagnosticsRow, error) {
	row := q.db.QueryRowContext(ctx, getBreakGlassTokenDiagnostics, tokenHash)
	var i GetBreakGlassTokenDiagnosticsRow
	err := row.Scan(&i.Used, &i.ExpiresAt, &i.ProjectID)
	return i, err
}

const listBreakGlassTokens = `-- name: ListBreakGlassTokens :many
SELECT id, scope, created_by, expires_at, used, COALESCE(used_by,''), COALESCE(incident_ref,'')
FROM break_glass_tokens
WHERE project_id = $1 OR project_id IS NULL
ORDER BY created_at DESC LIMIT 50
`

type ListBreakGlassTokensRow struct {
	ID          string
	Scope       string
	CreatedBy   string
	ExpiresAt   time.Time
	Used        bool
	UsedBy      string
	IncidentRef string
}

func (q *Queries) ListBreakGlassTokens(ctx context.Context, projectID sql.NullString) ([]ListBreakGlassTokensRow, error) {
	rows, err := q.db.QueryContext(ctx, listBreakGlassTokens, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBreakGlassTokensRow
	for rows.Next() {
		var i ListBreakGlassTokensRow
		if err := rows.Scan(
			&i.ID,
			&i.Scope,
			&i.CreatedBy,
			&i.ExpiresAt,
			&i.Used,
			&i.UsedBy,
			&i.IncidentRef,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
