// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: change_requests.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/lib/pq"
)

const changeRequestTargetExists = `-- name: ChangeRequestTargetExists :one
SELECT true AS exists FROM flag_environments fe JOIN flags f ON f.id = fe.flag_id
WHERE f.key = $1 AND fe.environment = $2 AND f.project_id = $3
`

type ChangeRequestTargetExistsParams struct {
	Key         string
	Environment string
	ProjectID   string
}

func (q *Queries) ChangeRequestTargetExists(ctx context.Context, arg ChangeRequestTargetExistsParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, changeRequestTargetExists, arg.Key, arg.Environment, arg.ProjectID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createChangeRequest = `-- name: CreateChangeRequest :one
INSERT INTO change_requests (flag_key, environment, requested_by, status, change_payload, project_id, required_approvals)
VALUES ($1, $2, $3, 'PENDING', $4, $5, $6)
RETURNING id, EXTRACT(EPOCH FROM created_at)::bigint AS created_at, EXTRACT(EPOCH FROM updated_at)::bigint AS updated_at
`

type CreateChangeRequestParams struct {
	FlagKey           string
	Environment       string
	RequestedBy       string
	ChangePayload     json.RawMessage
	ProjectID         sql.NullString
	RequiredApprovals int32
}

type CreateChangeRequestRow struct {
	ID        string
	CreatedAt int64
	UpdatedAt int64
}

func (q *Queries) CreateChangeRequest(ctx context.Context, arg CreateChangeRequestParams) (CreateChangeRequestRow, error) {
	row := q.db.QueryRowContext(ctx, createChangeRequest,
		arg.FlagKey,
		arg.Environment,
		arg.RequestedBy,
		arg.ChangePayload,
		arg.ProjectID,
		arg.RequiredApprovals,
	)
	var i CreateChangeRequestRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const finalizeAppliedChangeRequest = `-- name: FinalizeAppliedChangeRequest :exec
UPDATE change_requests SET approved_by = $1, status = 'APPLIED', updated_at = now() WHERE id = $2
`

type FinalizeAppliedChangeRequestParams struct {
	ApprovedBy []string
	ID         string
}

func (q *Queries) FinalizeAppliedChangeRequest(ctx context.Context, arg FinalizeAppliedChangeRequestParams) error {
	_, err := q.db.ExecContext(ctx, finalizeAppliedChangeRequest, pq.Array(arg.ApprovedBy), arg.ID)
	return err
}

const getChangeRequestForApproval = `-- name: GetChangeRequestForApproval :one
SELECT flag_key, environment, requested_by, change_payload, COALESCE(approved_by, '{}'), required_approvals
FROM change_requests
WHERE id = $1 AND project_id = $2 AND status = 'PENDING'
FOR UPDATE
`

type GetChangeRequestForApprovalParams struct {
	ID        string
	ProjectID sql.NullString
}

type GetChangeRequestForApprovalRow struct {
	FlagKey           string
	Environment       string
	RequestedBy       string
	ChangePayload     json.RawMessage
	ApprovedBy        []string
	RequiredApprovals int32
}

func (q *Queries) GetChangeRequestForApproval(ctx context.Context, arg GetChangeRequestForApprovalParams) (GetChangeRequestForApprovalRow, error) {
	row := q.db.QueryRowContext(ctx, getChangeRequestForApproval, arg.ID, arg.ProjectID)
	var i GetChangeRequestForApprovalRow
	err := row.Scan(
		&i.FlagKey,
		&i.Environment,
		&i.RequestedBy,
		&i.ChangePayload,
		pq.Array(&i.ApprovedBy),
		&i.RequiredApprovals,
	)
	return i, err
}

const getProjectRequiredApprovals = `-- name: GetProjectRequiredApprovals :one
SELECT required_approvals FROM projects WHERE id = $1
`

func (q *Queries) GetProjectRequiredApprovals(ctx context.Context, id string) (int32, error) {
	row := q.db.QueryRowContext(ctx, getProjectRequiredApprovals, id)
	var required_approvals int32
	err := row.Scan(&required_approvals)
	return required_approvals, err
}

const listChangeRequests = `-- name: ListChangeRequests :many
SELECT id, flag_key, environment, requested_by, status,
       change_payload, COALESCE(approved_by, '{}'),
       rejected_by, rejection_reason,
       EXTRACT(EPOCH FROM created_at)::bigint AS created_at,
       EXTRACT(EPOCH FROM updated_at)::bigint AS updated_at
FROM change_requests
WHERE status = $1 AND project_id = $2
ORDER BY created_at DESC
LIMIT 100
`

type ListChangeRequestsParams struct {
	Status    string
	ProjectID sql.NullString
}

type ListChangeRequestsRow struct {
	ID              string
	FlagKey         string
	Environment     string
	RequestedBy     string
	Status          string
	ChangePayload   json.RawMessage
	ApprovedBy      []string
	RejectedBy      sql.NullString
	RejectionReason sql.NullString
	CreatedAt       int64
	UpdatedAt       int64
}

func (q *Queries) ListChangeRequests(ctx context.Context, arg ListChangeRequestsParams) ([]ListChangeRequestsRow, error) {
	rows, err := q.db.QueryContext(ctx, listChangeRequests, arg.Status, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChangeRequestsRow
	for rows.Next() {
		var i ListChangeRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.FlagKey,
			&i.Environment,
			&i.RequestedBy,
			&i.Status,
			&i.ChangePayload,
			pq.Array(&i.ApprovedBy),
			&i.RejectedBy,
			&i.RejectionReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordApproval = `-- name: RecordApproval :exec
UPDATE change_requests SET approved_by = $1, status = $2, updated_at = now() WHERE id = $3
`

type RecordApprovalParams struct {
	ApprovedBy []string
	Status     string
	ID         string
}

func (q *Queries) RecordApproval(ctx context.Context, arg RecordApprovalParams) error {
	_, err := q.db.ExecContext(ctx, recordApproval, pq.Array(arg.ApprovedBy), arg.Status, arg.ID)
	return err
}

const rejectChangeRequest = `-- name: RejectChangeRequest :one
UPDATE change_requests
SET status           = 'REJECTED',
    rejected_by      = $1,
    rejection_reason = $2,
    updated_at       = $3
WHERE id = $4 AND status = 'PENDING' AND project_id = $5
RETURNING flag_key, environment
`

type RejectChangeRequestParams struct {
	RejectedBy      sql.NullString
	RejectionReason sql.NullString
	UpdatedAt       time.Time
	ID              string
	ProjectID       sql.NullString
}

type RejectChangeRequestRow struct {
	FlagKey     string
	Environment string
}

func (q *Queries) RejectChangeRequest(ctx context.Context, arg RejectChangeRequestParams) (RejectChangeRequestRow, error) {
	row := q.db.QueryRowContext(ctx, rejectChangeRequest,
		arg.RejectedBy,
		arg.RejectionReason,
		arg.UpdatedAt,
		arg.ID,
		arg.ProjectID,
	)
	var i RejectChangeRequestRow
	err := row.Scan(&i.FlagKey, &i.Environment)
	return i, err
}
