// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: compliance.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const changeRequestApprovalStats = `-- name: ChangeRequestApprovalStats :one
SELECT
    COUNT(*) FILTER (WHERE status IN ('APPROVED','APPLIED')) AS approved,
    COUNT(*) AS total
FROM change_requests
WHERE status != 'PENDING'
`

type ChangeRequestApprovalStatsRow struct {
	Approved int64
	Total    int64
}

func (q *Queries) ChangeRequestApprovalStats(ctx context.Context) (ChangeRequestApprovalStatsRow, error) {
	row := q.db.QueryRowContext(ctx, changeRequestApprovalStats)
	var i ChangeRequestApprovalStatsRow
	err := row.Scan(&i.Approved, &i.Total)
	return i, err
}

const countActiveServiceTokens = `-- name: CountActiveServiceTokens :one
SELECT COUNT(*) FROM service_tokens WHERE revoked_at IS NULL
`

func (q *Queries) CountActiveServiceTokens(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveServiceTokens)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAuditLogEntries = `-- name: CountAuditLogEntries :one
SELECT COUNT(*) FROM audit_log
`

func (q *Queries) CountAuditLogEntries(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAuditLogEntries)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRecentBreakGlassUses = `-- name: CountRecentBreakGlassUses :one
SELECT COUNT(*)
FROM break_glass_tokens
WHERE used = true
  AND used_at >= now() - INTERVAL '90 days'
`

func (q *Queries) CountRecentBreakGlassUses(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRecentBreakGlassUses)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRoleAssignments = `-- name: CountRoleAssignments :one
SELECT COUNT(*) FROM user_roles
`

func (q *Queries) CountRoleAssignments(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRoleAssignments)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const exportAuditLogForProject = `-- name: ExportAuditLogForProject :many
SELECT id, COALESCE(flag_key,'') AS flag_key, COALESCE(environment,'') AS environment, actor, event_type,
       COALESCE(prev_state::text,'null')::text AS prev_state, COALESCE(new_state::text,'null')::text AS new_state,
       COALESCE(ip_address,'') AS ip_address, COALESCE(prev_hash,'') AS prev_hash,
       EXTRACT(EPOCH FROM created_at)::bigint AS created_at,
       COALESCE(rekor_log_id,'') AS rekor_log_id, rekor_log_index
FROM audit_log
WHERE project_id = $1
ORDER BY created_at ASC
`

type ExportAuditLogForProjectRow struct {
	ID            string
	FlagKey       string
	Environment   string
	Actor         string
	EventType     string
	PrevState     string
	NewState      string
	IpAddress     string
	PrevHash      string
	CreatedAt     int64
	RekorLogID    string
	RekorLogIndex sql.NullInt64
}

func (q *Queries) ExportAuditLogForProject(ctx context.Context, projectID string) ([]ExportAuditLogForProjectRow, error) {
	rows, err := q.db.QueryContext(ctx, exportAuditLogForProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportAuditLogForProjectRow
	for rows.Next() {
		var i ExportAuditLogForProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.FlagKey,
			&i.Environment,
			&i.Actor,
			&i.EventType,
			&i.PrevState,
			&i.NewState,
			&i.IpAddress,
			&i.PrevHash,
			&i.CreatedAt,
			&i.RekorLogID,
			&i.RekorLogIndex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
