// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: environments.sql

package sqlcgen

import (
	"context"
)

const getEnvironmentSnapshot = `-- name: GetEnvironmentSnapshot :many
SELECT fe.flag_id, f.key, fe.environment, fe.enabled, fe.rollout_pct, f.safe_default,
       EXTRACT(EPOCH FROM fe.updated_at)::bigint AS updated_at
FROM flag_environments fe
JOIN flags f ON f.id = fe.flag_id
WHERE fe.environment = $1 AND f.state = 'ACTIVE' AND f.project_id = $2
ORDER BY f.key
`

type GetEnvironmentSnapshotParams struct {
	Environment string
	ProjectID   string
}

type GetEnvironmentSnapshotRow struct {
	FlagID      string
	Key         string
	Environment string
	Enabled     bool
	RolloutPct  int32
	SafeDefault string
	UpdatedAt   int64
}

func (q *Queries) GetEnvironmentSnapshot(ctx context.Context, arg GetEnvironmentSnapshotParams) ([]GetEnvironmentSnapshotRow, error) {
	rows, err := q.db.QueryContext(ctx, getEnvironmentSnapshot, arg.Environment, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEnvironmentSnapshotRow
	for rows.Next() {
		var i GetEnvironmentSnapshotRow
		if err := rows.Scan(
			&i.FlagID,
			&i.Key,
			&i.Environment,
			&i.Enabled,
			&i.RolloutPct,
			&i.SafeDefault,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEnvironmentSnapshotPrerequisites = `-- name: GetEnvironmentSnapshotPrerequisites :many
SELECT fp.flag_id, fp.id, fp.prereq_flag_key, fp.required_variation, fp.gate, fp.priority
FROM flag_prerequisites fp
JOIN flag_environments fe ON fe.flag_id = fp.flag_id
JOIN flags f ON f.id = fp.flag_id
WHERE fe.environment = $1 AND f.state = 'ACTIVE' AND f.project_id = $2
ORDER BY fp.flag_id, fp.priority ASC, fp.created_at ASC
`

type GetEnvironmentSnapshotPrerequisitesParams struct {
	Environment string
	ProjectID   string
}

type GetEnvironmentSnapshotPrerequisitesRow struct {
	FlagID            string
	ID                string
	PrereqFlagKey     string
	RequiredVariation string
	Gate              bool
	Priority          int32
}

func (q *Queries) GetEnvironmentSnapshotPrerequisites(ctx context.Context, arg GetEnvironmentSnapshotPrerequisitesParams) ([]GetEnvironmentSnapshotPrerequisitesRow, error) {
	rows, err := q.db.QueryContext(ctx, getEnvironmentSnapshotPrerequisites, arg.Environment, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEnvironmentSnapshotPrerequisitesRow
	for rows.Next() {
		var i GetEnvironmentSnapshotPrerequisitesRow
		if err := rows.Scan(
			&i.FlagID,
			&i.ID,
			&i.PrereqFlagKey,
			&i.RequiredVariation,
			&i.Gate,
			&i.Priority,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
