// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: flags.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const archiveFlag = `-- name: ArchiveFlag :execrows
UPDATE flags SET state='ARCHIVED', archived_at=now() WHERE key=$1 AND project_id=$2
`

type ArchiveFlagParams struct {
	Key       string
	ProjectID string
}

func (q *Queries) ArchiveFlag(ctx context.Context, arg ArchiveFlagParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, archiveFlag, arg.Key, arg.ProjectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const backfillAuditLogRekor = `-- name: BackfillAuditLogRekor :exec
UPDATE audit_log SET rekor_log_id=$1, rekor_log_index=$2 WHERE id=$3
`

type BackfillAuditLogRekorParams struct {
	RekorLogID    sql.NullString
	RekorLogIndex sql.NullInt64
	ID            string
}

// rekor_log_id/rekor_log_index are nullable (migration 009); the values
// passed at the call site are always real/valid when this fires (guarded by
// `if subErr != nil || logID == "" { return }` before it's ever called), but
// the columns are genuinely nullable so the generated params are sql.NullString/
// sql.NullInt64.
func (q *Queries) BackfillAuditLogRekor(ctx context.Context, arg BackfillAuditLogRekorParams) error {
	_, err := q.db.ExecContext(ctx, backfillAuditLogRekor, arg.RekorLogID, arg.RekorLogIndex, arg.ID)
	return err
}

const createDefaultFlagEnvironment = `-- name: CreateDefaultFlagEnvironment :exec
INSERT INTO flag_environments (flag_id, environment, enabled, rollout_pct, updated_by)
VALUES ($1,$2,false,0,$3) ON CONFLICT DO NOTHING
`

type CreateDefaultFlagEnvironmentParams struct {
	FlagID      string
	Environment string
	UpdatedBy   string
}

func (q *Queries) CreateDefaultFlagEnvironment(ctx context.Context, arg CreateDefaultFlagEnvironmentParams) error {
	_, err := q.db.ExecContext(ctx, createDefaultFlagEnvironment, arg.FlagID, arg.Environment, arg.UpdatedBy)
	return err
}

const createFlag = `-- name: CreateFlag :one
INSERT INTO flags (key, project_id, name, description, flag_type, state, owner_id, safe_default)
VALUES ($1,$2,$3,$4,$5,'ACTIVE',$6,$7)
RETURNING id, key, project_id, name, description, flag_type, state, owner_id, safe_default,
          EXTRACT(EPOCH FROM created_at)::bigint AS created_at, EXTRACT(EPOCH FROM updated_at)::bigint AS updated_at
`

type CreateFlagParams struct {
	Key         string
	ProjectID   string
	Name        string
	Description string
	FlagType    string
	OwnerID     string
	SafeDefault string
}

type CreateFlagRow struct {
	ID          string
	Key         string
	ProjectID   string
	Name        string
	Description string
	FlagType    string
	State       string
	OwnerID     string
	SafeDefault string
	CreatedAt   int64
	UpdatedAt   int64
}

func (q *Queries) CreateFlag(ctx context.Context, arg CreateFlagParams) (CreateFlagRow, error) {
	row := q.db.QueryRowContext(ctx, createFlag,
		arg.Key,
		arg.ProjectID,
		arg.Name,
		arg.Description,
		arg.FlagType,
		arg.OwnerID,
		arg.SafeDefault,
	)
	var i CreateFlagRow
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.FlagType,
		&i.State,
		&i.OwnerID,
		&i.SafeDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createFlagTombstone = `-- name: CreateFlagTombstone :exec
INSERT INTO flag_tombstones (key, archived_by) VALUES ($1,$2) ON CONFLICT DO NOTHING
`

type CreateFlagTombstoneParams struct {
	Key        string
	ArchivedBy string
}

func (q *Queries) CreateFlagTombstone(ctx context.Context, arg CreateFlagTombstoneParams) error {
	_, err := q.db.ExecContext(ctx, createFlagTombstone, arg.Key, arg.ArchivedBy)
	return err
}

const flagTombstoneExists = `-- name: FlagTombstoneExists :one
SELECT EXISTS(SELECT 1 FROM flag_tombstones WHERE key=$1)
`

func (q *Queries) FlagTombstoneExists(ctx context.Context, key string) (bool, error) {
	row := q.db.QueryRowContext(ctx, flagTombstoneExists, key)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getFlag = `-- name: GetFlag :one
SELECT id, key, project_id, name, description, flag_type, state, owner_id, safe_default,
       EXTRACT(EPOCH FROM created_at)::bigint AS created_at, EXTRACT(EPOCH FROM updated_at)::bigint AS updated_at
FROM flags WHERE key=$1 AND project_id=$2
`

type GetFlagParams struct {
	Key       string
	ProjectID string
}

type GetFlagRow struct {
	ID          string
	Key         string
	ProjectID   string
	Name        string
	Description string
	FlagType    string
	State       string
	OwnerID     string
	SafeDefault string
	CreatedAt   int64
	UpdatedAt   int64
}

func (q *Queries) GetFlag(ctx context.Context, arg GetFlagParams) (GetFlagRow, error) {
	row := q.db.QueryRowContext(ctx, getFlag, arg.Key, arg.ProjectID)
	var i GetFlagRow
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.FlagType,
		&i.State,
		&i.OwnerID,
		&i.SafeDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFlagEnvironmentPrevState = `-- name: GetFlagEnvironmentPrevState :one
SELECT fe.flag_id, f.key, fe.environment, fe.enabled, fe.rollout_pct, f.safe_default,
       EXTRACT(EPOCH FROM fe.updated_at)::bigint AS updated_at
FROM flag_environments fe JOIN flags f ON f.id = fe.flag_id
WHERE f.key=$1 AND fe.environment=$2 AND f.project_id=$3
`

type GetFlagEnvironmentPrevStateParams struct {
	Key         string
	Environment string
	ProjectID   string
}

type GetFlagEnvironmentPrevStateRow struct {
	FlagID      string
	Key         string
	Environment string
	Enabled     bool
	RolloutPct  int32
	SafeDefault string
	UpdatedAt   int64
}

// Shared by flags.go's UpdateEnvironment and change_requests.go's
// ApproveChangeRequest apply path — byte-identical SQL in both original
// call sites, so this is one query, not two.
func (q *Queries) GetFlagEnvironmentPrevState(ctx context.Context, arg GetFlagEnvironmentPrevStateParams) (GetFlagEnvironmentPrevStateRow, error) {
	row := q.db.QueryRowContext(ctx, getFlagEnvironmentPrevState, arg.Key, arg.Environment, arg.ProjectID)
	var i GetFlagEnvironmentPrevStateRow
	err := row.Scan(
		&i.FlagID,
		&i.Key,
		&i.Environment,
		&i.Enabled,
		&i.RolloutPct,
		&i.SafeDefault,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectRequireApproval = `-- name: GetProjectRequireApproval :one
SELECT require_approval FROM projects WHERE id = $1
`

func (q *Queries) GetProjectRequireApproval(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRowContext(ctx, getProjectRequireApproval, id)
	var require_approval bool
	err := row.Scan(&require_approval)
	return require_approval, err
}

const killSwitchFlagEnvironment = `-- name: KillSwitchFlagEnvironment :execrows
UPDATE flag_environments fe SET enabled=false, updated_at=now(), updated_by=$1
FROM flags f WHERE f.id=fe.flag_id AND f.key=$2 AND fe.environment=$3 AND f.project_id=$4
`

type KillSwitchFlagEnvironmentParams struct {
	UpdatedBy   string
	Key         string
	Environment string
	ProjectID   string
}

func (q *Queries) KillSwitchFlagEnvironment(ctx context.Context, arg KillSwitchFlagEnvironmentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, killSwitchFlagEnvironment,
		arg.UpdatedBy,
		arg.Key,
		arg.Environment,
		arg.ProjectID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listFlags = `-- name: ListFlags :many
SELECT f.id, f.key, f.project_id, f.name, f.description,
       f.flag_type, f.state, f.owner_id, f.safe_default,
       EXTRACT(EPOCH FROM f.created_at)::bigint AS created_at,
       EXTRACT(EPOCH FROM f.updated_at)::bigint AS updated_at
FROM flags f
WHERE f.project_id = $1 AND f.state != 'ARCHIVED'
ORDER BY f.created_at DESC
`

type ListFlagsRow struct {
	ID          string
	Key         string
	ProjectID   string
	Name        string
	Description string
	FlagType    string
	State       string
	OwnerID     string
	SafeDefault string
	CreatedAt   int64
	UpdatedAt   int64
}

func (q *Queries) ListFlags(ctx context.Context, projectID string) ([]ListFlagsRow, error) {
	rows, err := q.db.QueryContext(ctx, listFlags, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFlagsRow
	for rows.Next() {
		var i ListFlagsRow
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.ProjectID,
			&i.Name,
			&i.Description,
			&i.FlagType,
			&i.State,
			&i.OwnerID,
			&i.SafeDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFlagEnvironment = `-- name: UpdateFlagEnvironment :execrows
UPDATE flag_environments fe SET enabled=$1, rollout_pct=$2, updated_at=now(), updated_by=$3
FROM flags f WHERE f.id=fe.flag_id AND f.key=$4 AND fe.environment=$5 AND f.project_id=$6
`

type UpdateFlagEnvironmentParams struct {
	Enabled     bool
	RolloutPct  int32
	UpdatedBy   string
	Key         string
	Environment string
	ProjectID   string
}

// Shared by flags.go's UpdateEnvironment and change_requests.go's
// ApproveChangeRequest apply path — byte-identical SQL in both original
// call sites, so this is one query, not two.
func (q *Queries) UpdateFlagEnvironment(ctx context.Context, arg UpdateFlagEnvironmentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateFlagEnvironment,
		arg.Enabled,
		arg.RolloutPct,
		arg.UpdatedBy,
		arg.Key,
		arg.Environment,
		arg.ProjectID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
