// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: middleware.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"

	"github.com/sqlc-dev/pqtype"
)

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT request_hash, completed_at, response_status, response_body
FROM idempotency_keys
WHERE actor = $1 AND idempotency_key = $2 AND endpoint = $3
`

type GetIdempotencyKeyParams struct {
	Actor          string
	IdempotencyKey string
	Endpoint       string
}

type GetIdempotencyKeyRow struct {
	RequestHash    string
	CompletedAt    sql.NullTime
	ResponseStatus sql.NullInt32
	ResponseBody   pqtype.NullRawMessage
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (GetIdempotencyKeyRow, error) {
	row := q.db.QueryRowContext(ctx, getIdempotencyKey, arg.Actor, arg.IdempotencyKey, arg.Endpoint)
	var i GetIdempotencyKeyRow
	err := row.Scan(
		&i.RequestHash,
		&i.CompletedAt,
		&i.ResponseStatus,
		&i.ResponseBody,
	)
	return i, err
}

const getTokenWatermark = `-- name: GetTokenWatermark :one
SELECT valid_after FROM user_token_watermarks WHERE user_email = lower($1)
`

func (q *Queries) GetTokenWatermark(ctx context.Context, lower string) (time.Time, error) {
	row := q.db.QueryRowContext(ctx, getTokenWatermark, lower)
	var valid_after time.Time
	err := row.Scan(&valid_after)
	return valid_after, err
}

const getUserRole = `-- name: GetUserRole :one
SELECT role FROM user_roles WHERE user_id = $1 AND project_id = $2
`

type GetUserRoleParams struct {
	UserID    string
	ProjectID string
}

func (q *Queries) GetUserRole(ctx context.Context, arg GetUserRoleParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getUserRole, arg.UserID, arg.ProjectID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const insertIdempotencyKey = `-- name: InsertIdempotencyKey :one
INSERT INTO idempotency_keys (actor, idempotency_key, endpoint, request_hash)
VALUES ($1, $2, $3, $4)
ON CONFLICT (actor, idempotency_key, endpoint) DO NOTHING
RETURNING id
`

type InsertIdempotencyKeyParams struct {
	Actor          string
	IdempotencyKey string
	Endpoint       string
	RequestHash    string
}

func (q *Queries) InsertIdempotencyKey(ctx context.Context, arg InsertIdempotencyKeyParams) (string, error) {
	row := q.db.QueryRowContext(ctx, insertIdempotencyKey,
		arg.Actor,
		arg.IdempotencyKey,
		arg.Endpoint,
		arg.RequestHash,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const insertMFALogEvent = `-- name: InsertMFALogEvent :exec
INSERT INTO user_mfa_log (user_id, event_type) VALUES ($1, $2)
`

type InsertMFALogEventParams struct {
	UserID    string
	EventType string
}

func (q *Queries) InsertMFALogEvent(ctx context.Context, arg InsertMFALogEventParams) error {
	_, err := q.db.ExecContext(ctx, insertMFALogEvent, arg.UserID, arg.EventType)
	return err
}

const isProjectMember = `-- name: IsProjectMember :one
SELECT EXISTS(SELECT 1 FROM user_roles WHERE user_id=$1 AND project_id=$2)
`

type IsProjectMemberParams struct {
	UserID    string
	ProjectID string
}

func (q *Queries) IsProjectMember(ctx context.Context, arg IsProjectMemberParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isProjectMember, arg.UserID, arg.ProjectID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const purgeExpiredIdempotencyKeys = `-- name: PurgeExpiredIdempotencyKeys :execrows
DELETE FROM idempotency_keys WHERE expires_at < NOW()
`

func (q *Queries) PurgeExpiredIdempotencyKeys(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, purgeExpiredIdempotencyKeys)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const resolveServiceToken = `-- name: ResolveServiceToken :one
SELECT name, role, project_id FROM service_tokens
WHERE token_hash = $1 AND revoked_at IS NULL
`

type ResolveServiceTokenRow struct {
	Name      string
	Role      string
	ProjectID string
}

func (q *Queries) ResolveServiceToken(ctx context.Context, tokenHash sql.NullString) (ResolveServiceTokenRow, error) {
	row := q.db.QueryRowContext(ctx, resolveServiceToken, tokenHash)
	var i ResolveServiceTokenRow
	err := row.Scan(&i.Name, &i.Role, &i.ProjectID)
	return i, err
}

const updateIdempotencyKeyResponse = `-- name: UpdateIdempotencyKeyResponse :exec
UPDATE idempotency_keys
SET response_status = $1, response_body = $2, completed_at = now()
WHERE id = $3
`

type UpdateIdempotencyKeyResponseParams struct {
	ResponseStatus sql.NullInt32
	ResponseBody   pqtype.NullRawMessage
	ID             string
}

func (q *Queries) UpdateIdempotencyKeyResponse(ctx context.Context, arg UpdateIdempotencyKeyResponseParams) error {
	_, err := q.db.ExecContext(ctx, updateIdempotencyKeyResponse, arg.ResponseStatus, arg.ResponseBody, arg.ID)
	return err
}
