// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/sqlc-dev/pqtype"
)

type AuditLog struct {
	ID            string
	ProjectID     string
	FlagKey       sql.NullString
	Environment   sql.NullString
	Actor         string
	EventType     string
	PrevState     pqtype.NullRawMessage
	NewState      pqtype.NullRawMessage
	IpAddress     sql.NullString
	PrevHash      sql.NullString
	EntryHash     sql.NullString
	RekorLogID    sql.NullString
	RekorLogIndex sql.NullInt64
	CreatedAt     time.Time
}

type AuditLogDefault struct {
	ID            string
	ProjectID     string
	FlagKey       sql.NullString
	Environment   sql.NullString
	Actor         string
	EventType     string
	PrevState     pqtype.NullRawMessage
	NewState      pqtype.NullRawMessage
	IpAddress     sql.NullString
	PrevHash      sql.NullString
	EntryHash     sql.NullString
	RekorLogID    sql.NullString
	RekorLogIndex sql.NullInt64
	CreatedAt     time.Time
}

type AuditRetentionCheckpoint struct {
	ID                     string
	ProjectID              string
	FlagKey                string
	PrunedThroughHash      string
	PrunedThroughCreatedAt time.Time
	Signature              string
	CreatedAt              time.Time
}

type BreakGlassToken struct {
	ID          string
	Token       sql.NullString
	Scope       string
	CreatedBy   string
	ExpiresAt   time.Time
	Used        bool
	UsedAt      sql.NullTime
	UsedBy      sql.NullString
	IncidentRef sql.NullString
	CreatedAt   time.Time
	TokenHash   sql.NullString
	ProjectID   string
}

type ChangeRequest struct {
	ID                string
	FlagKey           string
	Environment       string
	RequestedBy       string
	Status            string
	ChangePayload     json.RawMessage
	ApprovedBy        []string
	RejectedBy        sql.NullString
	RejectionReason   sql.NullString
	CreatedAt         time.Time
	UpdatedAt         time.Time
	ProjectID         string
	RequiredApprovals int32
}

type ComplianceSnapshot struct {
	ID             string
	SnapshotWeek   time.Time
	TotalFlags     int32
	ActiveFlags    int32
	StaleFlags     int32
	RbacCoverage   float32
	ApprovalRate   float32
	BreakGlassUses int32
	HealthScore    float32
	GeneratedAt    time.Time
}

type CustomRole struct {
	ID          string
	ProjectID   string
	Name        string
	Permissions json.RawMessage
	CreatedAt   time.Time
}

type Flag struct {
	ID          string
	Key         string
	ProjectID   string
	Name        string
	Description string
	FlagType    string
	State       string
	OwnerID     string
	SafeDefault string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	ArchivedAt  sql.NullTime
	Embedding   interface{}
}

type FlagEnvironment struct {
	FlagID      string
	Environment string
	Enabled     bool
	RolloutPct  int32
	UpdatedAt   time.Time
	UpdatedBy   string
}

type FlagPrerequisite struct {
	ID                string
	FlagID            string
	PrereqFlagKey     string
	RequiredVariation string
	Gate              bool
	Priority          int32
	CreatedAt         time.Time
}

type FlagTombstone struct {
	Key        string
	ArchivedAt time.Time
	ArchivedBy string
	Reason     sql.NullString
}

type FlagVariation struct {
	ID          string
	FlagID      string
	Key         string
	Value       string
	Weight      int32
	Description sql.NullString
}

type IdempotencyKey struct {
	ID             string
	Actor          string
	IdempotencyKey string
	Endpoint       string
	RequestHash    string
	ResponseStatus sql.NullInt32
	ResponseBody   pqtype.NullRawMessage
	LockedAt       time.Time
	CompletedAt    sql.NullTime
	CreatedAt      time.Time
	ExpiresAt      time.Time
}

type InventoryLimit struct {
	ProjectID    string
	MaxFlags     int32
	CurrentCount int32
}

type Project struct {
	ID                string
	Name              string
	Slug              string
	CreatedAt         time.Time
	RequiredApprovals int32
	RequireApproval   bool
}

type ScheduledChange struct {
	ID            string
	FlagKey       string
	Environment   string
	ScheduledFor  time.Time
	ChangePayload json.RawMessage
	CreatedBy     string
	Status        string
	ExecutedAt    sql.NullTime
	CreatedAt     time.Time
	ErrorMessage  sql.NullString
	RetryCount    int32
	MaxRetries    int32
	NextRetryAt   sql.NullTime
	ProjectID     string
}

type ScimUser struct {
	ExternalID  string
	UserID      string
	Email       string
	DisplayName string
	Active      bool
	SyncedAt    time.Time
}

type Segment struct {
	ID          string
	ProjectID   string
	Name        string
	Description string
	Rules       json.RawMessage
	CreatedAt   time.Time
}

type ServiceToken struct {
	ID          string
	ProjectID   string
	Environment string
	Token       sql.NullString
	Name        string
	CreatedAt   time.Time
	RevokedAt   sql.NullTime
	Role        string
	TokenHash   sql.NullString
}

type SsoSession struct {
	ID        string
	UserEmail string
	Provider  string
	ExpiresAt time.Time
	CreatedAt time.Time
}

type SsoStateToken struct {
	State     string
	CreatedAt time.Time
	ExpiresAt time.Time
}

type TargetingRule struct {
	ID          string
	FlagID      string
	Environment string
	RuleType    string
	Attribute   string
	Operator    string
	Values      json.RawMessage
	Variation   string
	Priority    int32
}

type UserMfaLog struct {
	ID          string
	UserID      string
	EventType   string
	FlagKey     sql.NullString
	Environment sql.NullString
	CreatedAt   time.Time
}

type UserRole struct {
	UserID    string
	ProjectID string
	Role      string
	GrantedBy string
	GrantedAt time.Time
}

type UserTokenWatermark struct {
	UserEmail  string
	ValidAfter time.Time
}
