// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orphan_detector.sql

package sqlcgen

import (
	"context"
	"encoding/json"
)

const createOrphanChangeRequest = `-- name: CreateOrphanChangeRequest :exec
INSERT INTO change_requests
    (flag_key, environment, requested_by, status, change_payload, project_id)
VALUES ($1, 'production', 'system-orphan-detector', 'PENDING', $2, $3)
`

type CreateOrphanChangeRequestParams struct {
	FlagKey       string
	ChangePayload json.RawMessage
	ProjectID     string
}

func (q *Queries) CreateOrphanChangeRequest(ctx context.Context, arg CreateOrphanChangeRequestParams) error {
	_, err := q.db.ExecContext(ctx, createOrphanChangeRequest, arg.FlagKey, arg.ChangePayload, arg.ProjectID)
	return err
}

const listOrphanedFlags = `-- name: ListOrphanedFlags :many
SELECT f.key, f.owner_id, f.project_id
FROM flags f
WHERE f.state = 'ACTIVE'
  AND NOT EXISTS (
      SELECT 1 FROM scim_users su
      WHERE su.email = f.owner_id
        AND su.active = true
  )
ORDER BY f.key
`

type ListOrphanedFlagsRow struct {
	Key       string
	OwnerID   string
	ProjectID string
}

func (q *Queries) ListOrphanedFlags(ctx context.Context) ([]ListOrphanedFlagsRow, error) {
	rows, err := q.db.QueryContext(ctx, listOrphanedFlags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrphanedFlagsRow
	for rows.Next() {
		var i ListOrphanedFlagsRow
		if err := rows.Scan(&i.Key, &i.OwnerID, &i.ProjectID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
