// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: prerequisites.sql

package sqlcgen

import (
	"context"
)

const deletePrerequisite = `-- name: DeletePrerequisite :execrows
DELETE FROM flag_prerequisites fp
USING flags f
WHERE f.id = fp.flag_id
  AND f.key = $1
  AND fp.id = $2
  AND f.project_id = $3
`

type DeletePrerequisiteParams struct {
	Key       string
	ID        string
	ProjectID string
}

func (q *Queries) DeletePrerequisite(ctx context.Context, arg DeletePrerequisiteParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deletePrerequisite, arg.Key, arg.ID, arg.ProjectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const flagExistsInProject = `-- name: FlagExistsInProject :one
SELECT EXISTS(SELECT 1 FROM flags WHERE key = $1 AND project_id = $2)
`

type FlagExistsInProjectParams struct {
	Key       string
	ProjectID string
}

func (q *Queries) FlagExistsInProject(ctx context.Context, arg FlagExistsInProjectParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, flagExistsInProject, arg.Key, arg.ProjectID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertPrerequisite = `-- name: InsertPrerequisite :one
INSERT INTO flag_prerequisites (flag_id, prereq_flag_key, required_variation, gate, priority)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, flag_id, prereq_flag_key, required_variation, gate, priority,
          EXTRACT(EPOCH FROM created_at)::bigint AS created_at
`

type InsertPrerequisiteParams struct {
	FlagID            string
	PrereqFlagKey     string
	RequiredVariation string
	Gate              bool
	Priority          int32
}

type InsertPrerequisiteRow struct {
	ID                string
	FlagID            string
	PrereqFlagKey     string
	RequiredVariation string
	Gate              bool
	Priority          int32
	CreatedAt         int64
}

func (q *Queries) InsertPrerequisite(ctx context.Context, arg InsertPrerequisiteParams) (InsertPrerequisiteRow, error) {
	row := q.db.QueryRowContext(ctx, insertPrerequisite,
		arg.FlagID,
		arg.PrereqFlagKey,
		arg.RequiredVariation,
		arg.Gate,
		arg.Priority,
	)
	var i InsertPrerequisiteRow
	err := row.Scan(
		&i.ID,
		&i.FlagID,
		&i.PrereqFlagKey,
		&i.RequiredVariation,
		&i.Gate,
		&i.Priority,
		&i.CreatedAt,
	)
	return i, err
}

const listPrereqFlagKeysForFlag = `-- name: ListPrereqFlagKeysForFlag :many
SELECT fp.prereq_flag_key
FROM flag_prerequisites fp
JOIN flags f ON f.id = fp.flag_id
WHERE f.key = $1 AND f.project_id = $2
`

type ListPrereqFlagKeysForFlagParams struct {
	Key       string
	ProjectID string
}

func (q *Queries) ListPrereqFlagKeysForFlag(ctx context.Context, arg ListPrereqFlagKeysForFlagParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listPrereqFlagKeysForFlag, arg.Key, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var prereq_flag_key string
		if err := rows.Scan(&prereq_flag_key); err != nil {
			return nil, err
		}
		items = append(items, prereq_flag_key)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrerequisitesForFlag = `-- name: ListPrerequisitesForFlag :many
SELECT fp.id, fp.flag_id, fp.prereq_flag_key, fp.required_variation, fp.gate, fp.priority,
       EXTRACT(EPOCH FROM fp.created_at)::bigint AS created_at
FROM flag_prerequisites fp
JOIN flags f ON f.id = fp.flag_id
WHERE f.key = $1 AND f.project_id = $2
ORDER BY fp.priority ASC, fp.created_at ASC
`

type ListPrerequisitesForFlagParams struct {
	Key       string
	ProjectID string
}

type ListPrerequisitesForFlagRow struct {
	ID                string
	FlagID            string
	PrereqFlagKey     string
	RequiredVariation string
	Gate              bool
	Priority          int32
	CreatedAt         int64
}

func (q *Queries) ListPrerequisitesForFlag(ctx context.Context, arg ListPrerequisitesForFlagParams) ([]ListPrerequisitesForFlagRow, error) {
	rows, err := q.db.QueryContext(ctx, listPrerequisitesForFlag, arg.Key, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPrerequisitesForFlagRow
	for rows.Next() {
		var i ListPrerequisitesForFlagRow
		if err := rows.Scan(
			&i.ID,
			&i.FlagID,
			&i.PrereqFlagKey,
			&i.RequiredVariation,
			&i.Gate,
			&i.Priority,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveFlagIDByKey = `-- name: ResolveFlagIDByKey :one
SELECT id FROM flags WHERE key = $1 AND project_id = $2
`

type ResolveFlagIDByKeyParams struct {
	Key       string
	ProjectID string
}

func (q *Queries) ResolveFlagIDByKey(ctx context.Context, arg ResolveFlagIDByKeyParams) (string, error) {
	row := q.db.QueryRowContext(ctx, resolveFlagIDByKey, arg.Key, arg.ProjectID)
	var id string
	err := row.Scan(&id)
	return id, err
}
