// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
	"database/sql"
	"time"
)

type Querier interface {
	ApplyScheduledFlagEnvironmentUpdate(ctx context.Context, arg ApplyScheduledFlagEnvironmentUpdateParams) (int64, error)
	ChangeRequestApprovalStats(ctx context.Context) (ChangeRequestApprovalStatsRow, error)
	CountActiveServiceTokens(ctx context.Context) (int64, error)
	CountAuditLogEntries(ctx context.Context) (int64, error)
	CountRecentBreakGlassUses(ctx context.Context) (int64, error)
	CountRoleAssignments(ctx context.Context) (int64, error)
	CreateOrphanChangeRequest(ctx context.Context, arg CreateOrphanChangeRequestParams) error
	DeletePrerequisite(ctx context.Context, arg DeletePrerequisiteParams) (int64, error)
	FlagExistsInProject(ctx context.Context, arg FlagExistsInProjectParams) (bool, error)
	GetCurrentFlagEnvironmentState(ctx context.Context, arg GetCurrentFlagEnvironmentStateParams) (GetCurrentFlagEnvironmentStateRow, error)
	GetEnvironmentSnapshot(ctx context.Context, arg GetEnvironmentSnapshotParams) ([]GetEnvironmentSnapshotRow, error)
	GetEnvironmentSnapshotPrerequisites(ctx context.Context, arg GetEnvironmentSnapshotPrerequisitesParams) ([]GetEnvironmentSnapshotPrerequisitesRow, error)
	GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (GetIdempotencyKeyRow, error)
	GetScheduledChangeRetryState(ctx context.Context, id string) (GetScheduledChangeRetryStateRow, error)
	GetTokenWatermark(ctx context.Context, lower string) (time.Time, error)
	GetUserRole(ctx context.Context, arg GetUserRoleParams) (string, error)
	InsertIdempotencyKey(ctx context.Context, arg InsertIdempotencyKeyParams) (string, error)
	InsertMFALogEvent(ctx context.Context, arg InsertMFALogEventParams) error
	InsertPrerequisite(ctx context.Context, arg InsertPrerequisiteParams) (InsertPrerequisiteRow, error)
	IsProjectMember(ctx context.Context, arg IsProjectMemberParams) (bool, error)
	ListOrphanedFlags(ctx context.Context) ([]ListOrphanedFlagsRow, error)
	ListPrereqFlagKeysForFlag(ctx context.Context, arg ListPrereqFlagKeysForFlagParams) ([]string, error)
	ListPrerequisitesForFlag(ctx context.Context, arg ListPrerequisitesForFlagParams) ([]ListPrerequisitesForFlagRow, error)
	MarkScheduledChangeExecuted(ctx context.Context, id string) error
	MarkScheduledChangeFailedNoRetryState(ctx context.Context, arg MarkScheduledChangeFailedNoRetryStateParams) error
	MarkScheduledChangeFailedRetryPending(ctx context.Context, arg MarkScheduledChangeFailedRetryPendingParams) error
	MarkScheduledChangeFailedTerminal(ctx context.Context, arg MarkScheduledChangeFailedTerminalParams) error
	PurgeExpiredIdempotencyKeys(ctx context.Context) (int64, error)
	ResolveFlagIDByKey(ctx context.Context, arg ResolveFlagIDByKeyParams) (string, error)
	ResolveServiceToken(ctx context.Context, tokenHash sql.NullString) (ResolveServiceTokenRow, error)
	SelectDueScheduledChanges(ctx context.Context) ([]SelectDueScheduledChangesRow, error)
	UpdateIdempotencyKeyResponse(ctx context.Context, arg UpdateIdempotencyKeyResponseParams) error
}

var _ Querier = (*Queries)(nil)
