// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
	"database/sql"
	"time"
)

type Querier interface {
	ApplyScheduledFlagEnvironmentUpdate(ctx context.Context, arg ApplyScheduledFlagEnvironmentUpdateParams) (int64, error)
	CancelScheduledChange(ctx context.Context, arg CancelScheduledChangeParams) (int64, error)
	ChangeRequestApprovalStats(ctx context.Context) (ChangeRequestApprovalStatsRow, error)
	// $3 is nullable — NULL means "no project scope requested". A DATA-1b PR2
	// adversarial review found that an earlier version of this query used an
	// empty-string sentinel with the project_id COLUMN cast to ::text, which
	// silently turned this into a case-SENSITIVE text compare; project_id is a
	// client-controlled HTTP header with no case normalization, so a
	// same-project caller whose header casing merely differed from the
	// canonical lowercase stored value got wrongly rejected with 403. Using
	// sqlc.narg + casting the PARAMETER (not the column) to ::uuid in every
	// occurrence keeps $3 in one single, consistent type context (satisfying
	// the AUD-1 lesson this was originally written to avoid) while restoring
	// uuid's case-insensitive equality semantics the original dynamically-built
	// "project_id = $3::uuid" clause had.
	ConsumeBreakGlassToken(ctx context.Context, arg ConsumeBreakGlassTokenParams) (ConsumeBreakGlassTokenRow, error)
	CountActiveServiceTokens(ctx context.Context) (int64, error)
	CountAuditEntries(ctx context.Context) (int64, error)
	CountAuditLogEntries(ctx context.Context) (int64, error)
	CountRecentBreakGlassUses(ctx context.Context) (int64, error)
	CountRoleAssignments(ctx context.Context) (int64, error)
	CreateBreakGlassToken(ctx context.Context, arg CreateBreakGlassTokenParams) error
	CreateOrphanChangeRequest(ctx context.Context, arg CreateOrphanChangeRequestParams) error
	CreateScheduledChange(ctx context.Context, arg CreateScheduledChangeParams) (CreateScheduledChangeRow, error)
	DeletePrerequisite(ctx context.Context, arg DeletePrerequisiteParams) (int64, error)
	FlagExistsInProject(ctx context.Context, arg FlagExistsInProjectParams) (bool, error)
	FlagExistsInProjectNotArchived(ctx context.Context, arg FlagExistsInProjectNotArchivedParams) (bool, error)
	GetBreakGlassTokenDiagnostics(ctx context.Context, tokenHash sql.NullString) (GetBreakGlassTokenDiagnosticsRow, error)
	GetCurrentFlagEnvironmentState(ctx context.Context, arg GetCurrentFlagEnvironmentStateParams) (GetCurrentFlagEnvironmentStateRow, error)
	GetEnvironmentSnapshot(ctx context.Context, arg GetEnvironmentSnapshotParams) ([]GetEnvironmentSnapshotRow, error)
	GetEnvironmentSnapshotPrerequisites(ctx context.Context, arg GetEnvironmentSnapshotPrerequisitesParams) ([]GetEnvironmentSnapshotPrerequisitesRow, error)
	GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (GetIdempotencyKeyRow, error)
	GetScheduledChangeRetryState(ctx context.Context, id string) (GetScheduledChangeRetryStateRow, error)
	GetScheduledChangeStatus(ctx context.Context, arg GetScheduledChangeStatusParams) (string, error)
	GetTokenWatermark(ctx context.Context, lower string) (time.Time, error)
	GetUserRole(ctx context.Context, arg GetUserRoleParams) (string, error)
	// Deliberately NOT converted to sqlc: the combined "render prev_state/
	// new_state exactly as Postgres will store them, and read the chain tip's
	// entry_hash, in one round-trip" query in audit.go's Append. Empirically
	// confirmed (a throwaway probe against real Postgres) that sqlc infers a
	// NON-nullable Go output type for a bare `sqlc.narg(x)::jsonb[::text]`
	// computed column no matter how the cast is wrapped (CAST(...AS text),
	// an extra dummy column, a standalone SELECT with no FROM) — even though
	// the parameter is genuinely nullable and IS null on most Append calls
	// (most audit events have an empty PrevState or NewState). Scanning that
	// NULL into the generated non-nullable string/json.RawMessage destination
	// is a hard database/sql error, reproduced live: "unsupported Scan, storing
	// driver.Value type <nil> into type *json.RawMessage". This is the same
	// CRITICAL bug class DATA-1b PR 1/4 found for NULL-into-plain-string, just
	// for a computed expression sqlc has no override mechanism for. Matches
	// PR 1's precedent for ExportAuditLog: not every query safely fits sqlc's
	// generated shape, and this is the audit hash chain — the wrong call here
	// is not worth whatever uniformity converting it would buy.
	InsertAuditEntry(ctx context.Context, arg InsertAuditEntryParams) error
	InsertIdempotencyKey(ctx context.Context, arg InsertIdempotencyKeyParams) (string, error)
	InsertMFALogEvent(ctx context.Context, arg InsertMFALogEventParams) error
	InsertPrerequisite(ctx context.Context, arg InsertPrerequisiteParams) (InsertPrerequisiteRow, error)
	IsProjectMember(ctx context.Context, arg IsProjectMemberParams) (bool, error)
	// The project_id parameter is cast to ::uuid (never the column to text) on
	// both sides of the OR — casting a uuid column to text to compare it against
	// a bare parameter silently turns a case-insensitive uuid comparison into a
	// case-sensitive text one (DATA-1b PR 2/4 found and fixed exactly this bug
	// in breakglass.sql's ConsumeBreakGlassToken). This query already followed
	// the safe pattern before any sqlc conversion — preserved as-is.
	ListAuditLogForVerification(ctx context.Context, projectID sql.NullString) ([]ListAuditLogForVerificationRow, error)
	ListAuditRetentionCheckpoints(ctx context.Context, projectID sql.NullString) ([]ListAuditRetentionCheckpointsRow, error)
	ListBreakGlassTokens(ctx context.Context, projectID sql.NullString) ([]ListBreakGlassTokensRow, error)
	ListOrphanedFlags(ctx context.Context) ([]ListOrphanedFlagsRow, error)
	ListPrereqFlagKeysForFlag(ctx context.Context, arg ListPrereqFlagKeysForFlagParams) ([]string, error)
	ListPrerequisitesForFlag(ctx context.Context, arg ListPrerequisitesForFlagParams) ([]ListPrerequisitesForFlagRow, error)
	// $3/$4 are always plain strings, "" meaning "no filter" — a single static
	// query using an empty-string sentinel instead of conditionally appending
	// clauses with a variable placeholder count. environment/status are both
	// plain TEXT columns compared to a TEXT parameter, so (unlike a uuid column)
	// there is no cast-direction ambiguity to worry about here at all.
	ListScheduledChanges(ctx context.Context, arg ListScheduledChangesParams) ([]ListScheduledChangesRow, error)
	// Serializes appends to one chain. pg_advisory_xact_lock releases
	// automatically at commit/rollback, so a crashed writer cannot wedge it.
	// flag_key is the plain (possibly empty) string, not a NULL sentinel — "" is
	// a perfectly valid hashtext() input and locks by it consistently.
	LockAuditChain(ctx context.Context, arg LockAuditChainParams) error
	MarkScheduledChangeExecuted(ctx context.Context, id string) error
	MarkScheduledChangeFailedNoRetryState(ctx context.Context, arg MarkScheduledChangeFailedNoRetryStateParams) error
	MarkScheduledChangeFailedRetryPending(ctx context.Context, arg MarkScheduledChangeFailedRetryPendingParams) error
	MarkScheduledChangeFailedTerminal(ctx context.Context, arg MarkScheduledChangeFailedTerminalParams) error
	PurgeExpiredIdempotencyKeys(ctx context.Context) (int64, error)
	ResolveFlagIDByKey(ctx context.Context, arg ResolveFlagIDByKeyParams) (string, error)
	ResolveServiceToken(ctx context.Context, tokenHash sql.NullString) (ResolveServiceTokenRow, error)
	SelectDueScheduledChanges(ctx context.Context) ([]SelectDueScheduledChangesRow, error)
	UpdateIdempotencyKeyResponse(ctx context.Context, arg UpdateIdempotencyKeyResponseParams) error
}

var _ Querier = (*Queries)(nil)
