// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scheduler.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"encoding/json"
)

const applyScheduledFlagEnvironmentUpdate = `-- name: ApplyScheduledFlagEnvironmentUpdate :execrows
UPDATE flag_environments fe
SET enabled = $1, rollout_pct = $2, updated_at = now(), updated_by = 'scheduler'
FROM flags f
WHERE f.id = fe.flag_id AND f.key = $3 AND fe.environment = $4 AND f.project_id = $5
`

type ApplyScheduledFlagEnvironmentUpdateParams struct {
	Enabled     bool
	RolloutPct  int32
	Key         string
	Environment string
	ProjectID   string
}

func (q *Queries) ApplyScheduledFlagEnvironmentUpdate(ctx context.Context, arg ApplyScheduledFlagEnvironmentUpdateParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, applyScheduledFlagEnvironmentUpdate,
		arg.Enabled,
		arg.RolloutPct,
		arg.Key,
		arg.Environment,
		arg.ProjectID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getCurrentFlagEnvironmentState = `-- name: GetCurrentFlagEnvironmentState :one
SELECT fe.enabled, fe.rollout_pct, fe.flag_id
FROM flag_environments fe
JOIN flags f ON f.id = fe.flag_id
WHERE f.key = $1 AND fe.environment = $2 AND f.project_id = $3
`

type GetCurrentFlagEnvironmentStateParams struct {
	Key         string
	Environment string
	ProjectID   string
}

type GetCurrentFlagEnvironmentStateRow struct {
	Enabled    bool
	RolloutPct int32
	FlagID     string
}

func (q *Queries) GetCurrentFlagEnvironmentState(ctx context.Context, arg GetCurrentFlagEnvironmentStateParams) (GetCurrentFlagEnvironmentStateRow, error) {
	row := q.db.QueryRowContext(ctx, getCurrentFlagEnvironmentState, arg.Key, arg.Environment, arg.ProjectID)
	var i GetCurrentFlagEnvironmentStateRow
	err := row.Scan(&i.Enabled, &i.RolloutPct, &i.FlagID)
	return i, err
}

const getScheduledChangeRetryState = `-- name: GetScheduledChangeRetryState :one
SELECT retry_count, max_retries FROM scheduled_changes WHERE id = $1
`

type GetScheduledChangeRetryStateRow struct {
	RetryCount int32
	MaxRetries int32
}

func (q *Queries) GetScheduledChangeRetryState(ctx context.Context, id string) (GetScheduledChangeRetryStateRow, error) {
	row := q.db.QueryRowContext(ctx, getScheduledChangeRetryState, id)
	var i GetScheduledChangeRetryStateRow
	err := row.Scan(&i.RetryCount, &i.MaxRetries)
	return i, err
}

const markScheduledChangeExecuted = `-- name: MarkScheduledChangeExecuted :exec
UPDATE scheduled_changes
SET status = 'EXECUTED', executed_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkScheduledChangeExecuted(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, markScheduledChangeExecuted, id)
	return err
}

const markScheduledChangeFailedNoRetryState = `-- name: MarkScheduledChangeFailedNoRetryState :exec
UPDATE scheduled_changes
SET status = 'FAILED', error_message = $1
WHERE id = $2
`

type MarkScheduledChangeFailedNoRetryStateParams struct {
	ErrorMessage sql.NullString
	ID           string
}

func (q *Queries) MarkScheduledChangeFailedNoRetryState(ctx context.Context, arg MarkScheduledChangeFailedNoRetryStateParams) error {
	_, err := q.db.ExecContext(ctx, markScheduledChangeFailedNoRetryState, arg.ErrorMessage, arg.ID)
	return err
}

const markScheduledChangeFailedRetryPending = `-- name: MarkScheduledChangeFailedRetryPending :exec
UPDATE scheduled_changes
SET status = 'FAILED', error_message = $1, retry_count = $2, next_retry_at = $3
WHERE id = $4
`

type MarkScheduledChangeFailedRetryPendingParams struct {
	ErrorMessage sql.NullString
	RetryCount   int32
	NextRetryAt  sql.NullTime
	ID           string
}

func (q *Queries) MarkScheduledChangeFailedRetryPending(ctx context.Context, arg MarkScheduledChangeFailedRetryPendingParams) error {
	_, err := q.db.ExecContext(ctx, markScheduledChangeFailedRetryPending,
		arg.ErrorMessage,
		arg.RetryCount,
		arg.NextRetryAt,
		arg.ID,
	)
	return err
}

const markScheduledChangeFailedTerminal = `-- name: MarkScheduledChangeFailedTerminal :exec
UPDATE scheduled_changes
SET status = 'FAILED', error_message = $1, retry_count = $2, next_retry_at = NULL
WHERE id = $3
`

type MarkScheduledChangeFailedTerminalParams struct {
	ErrorMessage sql.NullString
	RetryCount   int32
	ID           string
}

func (q *Queries) MarkScheduledChangeFailedTerminal(ctx context.Context, arg MarkScheduledChangeFailedTerminalParams) error {
	_, err := q.db.ExecContext(ctx, markScheduledChangeFailedTerminal, arg.ErrorMessage, arg.RetryCount, arg.ID)
	return err
}

const selectDueScheduledChanges = `-- name: SelectDueScheduledChanges :many
SELECT id, flag_key, environment, change_payload, project_id
FROM scheduled_changes
WHERE (status = 'PENDING' AND scheduled_for <= NOW())
   OR (status = 'FAILED' AND retry_count < max_retries AND next_retry_at <= NOW())
ORDER BY scheduled_for ASC
FOR UPDATE SKIP LOCKED
`

type SelectDueScheduledChangesRow struct {
	ID            string
	FlagKey       string
	Environment   string
	ChangePayload json.RawMessage
	ProjectID     string
}

func (q *Queries) SelectDueScheduledChanges(ctx context.Context) ([]SelectDueScheduledChangesRow, error) {
	rows, err := q.db.QueryContext(ctx, selectDueScheduledChanges)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectDueScheduledChangesRow
	for rows.Next() {
		var i SelectDueScheduledChangesRow
		if err := rows.Scan(
			&i.ID,
			&i.FlagKey,
			&i.Environment,
			&i.ChangePayload,
			&i.ProjectID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
