// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scheduled.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const cancelScheduledChange = `-- name: CancelScheduledChange :execrows
UPDATE scheduled_changes
SET status = 'CANCELLED'
WHERE id = $1 AND flag_key = $2 AND status = 'PENDING' AND project_id = $3
`

type CancelScheduledChangeParams struct {
	ID        string
	FlagKey   string
	ProjectID sql.NullString
}

func (q *Queries) CancelScheduledChange(ctx context.Context, arg CancelScheduledChangeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, cancelScheduledChange, arg.ID, arg.FlagKey, arg.ProjectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createScheduledChange = `-- name: CreateScheduledChange :one
INSERT INTO scheduled_changes
    (id, flag_key, environment, scheduled_for, change_payload, created_by, status, project_id)
VALUES ($1, $2, $3, $4, $5, $6, 'PENDING', $7)
RETURNING
    id, flag_key, environment,
    EXTRACT(EPOCH FROM scheduled_for)::bigint AS scheduled_for,
    change_payload, created_by, status,
    executed_at,
    error_message,
    EXTRACT(EPOCH FROM created_at)::bigint AS created_at
`

type CreateScheduledChangeParams struct {
	ID            string
	FlagKey       string
	Environment   string
	ScheduledFor  time.Time
	ChangePayload json.RawMessage
	CreatedBy     string
	ProjectID     sql.NullString
}

type CreateScheduledChangeRow struct {
	ID            string
	FlagKey       string
	Environment   string
	ScheduledFor  int64
	ChangePayload json.RawMessage
	CreatedBy     string
	Status        string
	ExecutedAt    sql.NullTime
	ErrorMessage  sql.NullString
	CreatedAt     int64
}

func (q *Queries) CreateScheduledChange(ctx context.Context, arg CreateScheduledChangeParams) (CreateScheduledChangeRow, error) {
	row := q.db.QueryRowContext(ctx, createScheduledChange,
		arg.ID,
		arg.FlagKey,
		arg.Environment,
		arg.ScheduledFor,
		arg.ChangePayload,
		arg.CreatedBy,
		arg.ProjectID,
	)
	var i CreateScheduledChangeRow
	err := row.Scan(
		&i.ID,
		&i.FlagKey,
		&i.Environment,
		&i.ScheduledFor,
		&i.ChangePayload,
		&i.CreatedBy,
		&i.Status,
		&i.ExecutedAt,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}

const flagExistsInProjectNotArchived = `-- name: FlagExistsInProjectNotArchived :one
SELECT EXISTS(SELECT 1 FROM flags WHERE key=$1 AND project_id=$2 AND state != 'ARCHIVED')
`

type FlagExistsInProjectNotArchivedParams struct {
	Key       string
	ProjectID string
}

func (q *Queries) FlagExistsInProjectNotArchived(ctx context.Context, arg FlagExistsInProjectNotArchivedParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, flagExistsInProjectNotArchived, arg.Key, arg.ProjectID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getScheduledChangeStatus = `-- name: GetScheduledChangeStatus :one
SELECT status FROM scheduled_changes WHERE id=$1 AND flag_key=$2 AND project_id=$3
`

type GetScheduledChangeStatusParams struct {
	ID        string
	FlagKey   string
	ProjectID sql.NullString
}

func (q *Queries) GetScheduledChangeStatus(ctx context.Context, arg GetScheduledChangeStatusParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getScheduledChangeStatus, arg.ID, arg.FlagKey, arg.ProjectID)
	var status string
	err := row.Scan(&status)
	return status, err
}

const listScheduledChanges = `-- name: ListScheduledChanges :many
SELECT
    id, flag_key, environment,
    EXTRACT(EPOCH FROM scheduled_for)::bigint AS scheduled_for,
    change_payload, created_by, status,
    executed_at,
    error_message,
    EXTRACT(EPOCH FROM created_at)::bigint AS created_at
FROM scheduled_changes
WHERE flag_key = $1 AND project_id = $2
  AND ($3::text = '' OR environment = $3::text)
  AND ($4::text = '' OR status = $4::text)
ORDER BY scheduled_for ASC
`

type ListScheduledChangesParams struct {
	FlagKey           string
	ProjectID         sql.NullString
	EnvironmentFilter string
	StatusFilter      string
}

type ListScheduledChangesRow struct {
	ID            string
	FlagKey       string
	Environment   string
	ScheduledFor  int64
	ChangePayload json.RawMessage
	CreatedBy     string
	Status        string
	ExecutedAt    sql.NullTime
	ErrorMessage  sql.NullString
	CreatedAt     int64
}

// $3/$4 are always plain strings, "" meaning "no filter" — a single static
// query using an empty-string sentinel instead of conditionally appending
// clauses with a variable placeholder count. environment/status are both
// plain TEXT columns compared to a TEXT parameter, so (unlike a uuid column)
// there is no cast-direction ambiguity to worry about here at all.
func (q *Queries) ListScheduledChanges(ctx context.Context, arg ListScheduledChangesParams) ([]ListScheduledChangesRow, error) {
	rows, err := q.db.QueryContext(ctx, listScheduledChanges,
		arg.FlagKey,
		arg.ProjectID,
		arg.EnvironmentFilter,
		arg.StatusFilter,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListScheduledChangesRow
	for rows.Next() {
		var i ListScheduledChangesRow
		if err := rows.Scan(
			&i.ID,
			&i.FlagKey,
			&i.Environment,
			&i.ScheduledFor,
			&i.ChangePayload,
			&i.CreatedBy,
			&i.Status,
			&i.ExecutedAt,
			&i.ErrorMessage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
