// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scim.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"encoding/json"
)

const createSCIMOrphanChangeRequest = `-- name: CreateSCIMOrphanChangeRequest :exec
INSERT INTO change_requests
    (flag_key, environment, requested_by, status, change_payload, project_id)
VALUES ($1, 'production', 'system', 'PENDING', $2, $3)
`

type CreateSCIMOrphanChangeRequestParams struct {
	FlagKey       string
	ChangePayload json.RawMessage
	ProjectID     sql.NullString
}

// A separate query from orphan_detector.sql's CreateOrphanChangeRequest even
// though the column list is identical: requested_by differs ('system' here
// vs 'system-orphan-detector' there), so sharing one query would require
// turning that literal into a bound parameter and touching
// orphan_detector.go's already-shipped, out-of-scope call site.
func (q *Queries) CreateSCIMOrphanChangeRequest(ctx context.Context, arg CreateSCIMOrphanChangeRequestParams) error {
	_, err := q.db.ExecContext(ctx, createSCIMOrphanChangeRequest, arg.FlagKey, arg.ChangePayload, arg.ProjectID)
	return err
}

const deprovisionSCIMUser = `-- name: DeprovisionSCIMUser :one
UPDATE scim_users
SET active = false, synced_at = now()
WHERE external_id = $1
RETURNING email
`

func (q *Queries) DeprovisionSCIMUser(ctx context.Context, externalID string) (string, error) {
	row := q.db.QueryRowContext(ctx, deprovisionSCIMUser, externalID)
	var email string
	err := row.Scan(&email)
	return email, err
}

const getSCIMUser = `-- name: GetSCIMUser :one
SELECT external_id, user_id, email, display_name, active
FROM scim_users
WHERE external_id = $1
`

type GetSCIMUserRow struct {
	ExternalID  string
	UserID      string
	Email       string
	DisplayName string
	Active      bool
}

func (q *Queries) GetSCIMUser(ctx context.Context, externalID string) (GetSCIMUserRow, error) {
	row := q.db.QueryRowContext(ctx, getSCIMUser, externalID)
	var i GetSCIMUserRow
	err := row.Scan(
		&i.ExternalID,
		&i.UserID,
		&i.Email,
		&i.DisplayName,
		&i.Active,
	)
	return i, err
}

const getSCIMUserEmail = `-- name: GetSCIMUserEmail :one
SELECT email FROM scim_users WHERE external_id = $1
`

func (q *Queries) GetSCIMUserEmail(ctx context.Context, externalID string) (string, error) {
	row := q.db.QueryRowContext(ctx, getSCIMUserEmail, externalID)
	var email string
	err := row.Scan(&email)
	return email, err
}

const listActiveFlagsByOwner = `-- name: ListActiveFlagsByOwner :many
SELECT key, project_id FROM flags
WHERE owner_id = $1 AND state = 'ACTIVE'
`

type ListActiveFlagsByOwnerRow struct {
	Key       string
	ProjectID string
}

func (q *Queries) ListActiveFlagsByOwner(ctx context.Context, ownerID string) ([]ListActiveFlagsByOwnerRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveFlagsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveFlagsByOwnerRow
	for rows.Next() {
		var i ListActiveFlagsByOwnerRow
		if err := rows.Scan(&i.Key, &i.ProjectID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSCIMUsers = `-- name: ListSCIMUsers :many
SELECT external_id, user_id, email, display_name, active
FROM scim_users
ORDER BY synced_at DESC
`

type ListSCIMUsersRow struct {
	ExternalID  string
	UserID      string
	Email       string
	DisplayName string
	Active      bool
}

func (q *Queries) ListSCIMUsers(ctx context.Context) ([]ListSCIMUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listSCIMUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSCIMUsersRow
	for rows.Next() {
		var i ListSCIMUsersRow
		if err := rows.Scan(
			&i.ExternalID,
			&i.UserID,
			&i.Email,
			&i.DisplayName,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeUserRoles = `-- name: RevokeUserRoles :many
DELETE FROM user_roles WHERE lower(user_id) = lower($1::text) RETURNING project_id
`

// Case-insensitive on purpose (SEC-5): user_roles.user_id is populated
// out-of-band with no case guarantee relative to what an IdP later asserts.
// Matching case-insensitively only ever revokes MORE broadly, never less —
// the safe direction to err in for a deprovisioning action. Do not collapse
// to `user_id = lower($1)`, which would make the column-side comparison
// case-sensitive again.
func (q *Queries) RevokeUserRoles(ctx context.Context, userEmail string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, revokeUserRoles, userEmail)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var project_id string
		if err := rows.Scan(&project_id); err != nil {
			return nil, err
		}
		items = append(items, project_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSCIMUser = `-- name: UpdateSCIMUser :execrows
UPDATE scim_users
SET user_id      = $1,
    email        = $2,
    display_name = $3,
    active       = $4,
    synced_at    = now()
WHERE external_id = $5
`

type UpdateSCIMUserParams struct {
	UserID      string
	Email       string
	DisplayName string
	Active      bool
	ExternalID  string
}

func (q *Queries) UpdateSCIMUser(ctx context.Context, arg UpdateSCIMUserParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateSCIMUser,
		arg.UserID,
		arg.Email,
		arg.DisplayName,
		arg.Active,
		arg.ExternalID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertSCIMUser = `-- name: UpsertSCIMUser :exec
INSERT INTO scim_users (external_id, user_id, email, display_name, active, synced_at)
VALUES ($1, $2, $3, $4, $5, now())
ON CONFLICT (external_id) DO UPDATE
    SET user_id      = EXCLUDED.user_id,
        email        = EXCLUDED.email,
        display_name = EXCLUDED.display_name,
        active       = EXCLUDED.active,
        synced_at    = now()
`

type UpsertSCIMUserParams struct {
	ExternalID  string
	UserID      string
	Email       string
	DisplayName string
	Active      bool
}

func (q *Queries) UpsertSCIMUser(ctx context.Context, arg UpsertSCIMUserParams) error {
	_, err := q.db.ExecContext(ctx, upsertSCIMUser,
		arg.ExternalID,
		arg.UserID,
		arg.Email,
		arg.DisplayName,
		arg.Active,
	)
	return err
}

const upsertUserTokenWatermark = `-- name: UpsertUserTokenWatermark :exec
INSERT INTO user_token_watermarks (user_email, valid_after)
VALUES (lower($1::text), now())
ON CONFLICT (user_email) DO UPDATE SET valid_after = now()
`

func (q *Queries) UpsertUserTokenWatermark(ctx context.Context, userEmail string) error {
	_, err := q.db.ExecContext(ctx, upsertUserTokenWatermark, userEmail)
	return err
}
