// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: targeting_rules.sql

package sqlcgen

import (
	"context"
	"encoding/json"
)

const deleteTargetingRule = `-- name: DeleteTargetingRule :execrows
DELETE FROM targeting_rules tr
USING flags f
WHERE f.id = tr.flag_id
  AND f.key = $1
  AND tr.environment = $2
  AND tr.id = $3
  AND f.project_id = $4
`

type DeleteTargetingRuleParams struct {
	Key         string
	Environment string
	ID          string
	ProjectID   string
}

func (q *Queries) DeleteTargetingRule(ctx context.Context, arg DeleteTargetingRuleParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTargetingRule,
		arg.Key,
		arg.Environment,
		arg.ID,
		arg.ProjectID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertTargetingRule = `-- name: InsertTargetingRule :one
INSERT INTO targeting_rules (flag_id, environment, rule_type, attribute, operator, values, variation, priority)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, flag_id, environment, rule_type, attribute, operator, values, variation, priority,
          EXTRACT(EPOCH FROM created_at)::bigint AS created_at
`

type InsertTargetingRuleParams struct {
	FlagID      string
	Environment string
	RuleType    string
	Attribute   string
	Operator    string
	Values      json.RawMessage
	Variation   string
	Priority    int32
}

type InsertTargetingRuleRow struct {
	ID          string
	FlagID      string
	Environment string
	RuleType    string
	Attribute   string
	Operator    string
	Values      json.RawMessage
	Variation   string
	Priority    int32
	CreatedAt   int64
}

func (q *Queries) InsertTargetingRule(ctx context.Context, arg InsertTargetingRuleParams) (InsertTargetingRuleRow, error) {
	row := q.db.QueryRowContext(ctx, insertTargetingRule,
		arg.FlagID,
		arg.Environment,
		arg.RuleType,
		arg.Attribute,
		arg.Operator,
		arg.Values,
		arg.Variation,
		arg.Priority,
	)
	var i InsertTargetingRuleRow
	err := row.Scan(
		&i.ID,
		&i.FlagID,
		&i.Environment,
		&i.RuleType,
		&i.Attribute,
		&i.Operator,
		&i.Values,
		&i.Variation,
		&i.Priority,
		&i.CreatedAt,
	)
	return i, err
}

const listTargetingRulesForFlag = `-- name: ListTargetingRulesForFlag :many
SELECT tr.id, tr.flag_id, tr.environment, tr.rule_type, tr.attribute, tr.operator, tr.values, tr.variation, tr.priority,
       EXTRACT(EPOCH FROM tr.created_at)::bigint AS created_at
FROM targeting_rules tr
JOIN flags f ON f.id = tr.flag_id
WHERE f.key = $1 AND tr.environment = $2 AND f.project_id = $3
ORDER BY tr.priority ASC, tr.created_at ASC
`

type ListTargetingRulesForFlagParams struct {
	Key         string
	Environment string
	ProjectID   string
}

type ListTargetingRulesForFlagRow struct {
	ID          string
	FlagID      string
	Environment string
	RuleType    string
	Attribute   string
	Operator    string
	Values      json.RawMessage
	Variation   string
	Priority    int32
	CreatedAt   int64
}

func (q *Queries) ListTargetingRulesForFlag(ctx context.Context, arg ListTargetingRulesForFlagParams) ([]ListTargetingRulesForFlagRow, error) {
	rows, err := q.db.QueryContext(ctx, listTargetingRulesForFlag, arg.Key, arg.Environment, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTargetingRulesForFlagRow
	for rows.Next() {
		var i ListTargetingRulesForFlagRow
		if err := rows.Scan(
			&i.ID,
			&i.FlagID,
			&i.Environment,
			&i.RuleType,
			&i.Attribute,
			&i.Operator,
			&i.Values,
			&i.Variation,
			&i.Priority,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
